import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DasboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en">
        <body className={inter.className}>
            <div className="sidebar">
                {/* Sidebar content goes here */}
            </div>
            <div className="main-content">
                {children}
            </div>
        </body>
    </html>
);
}
